# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'substring_game_qt2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import random


class Ui_MainWindow2(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(702, 649)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 15, 44, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.edit1 = QtWidgets.QTextEdit(self.centralwidget)
        self.edit1.setGeometry(QtCore.QRect(91, 140, 209, 290))
        self.edit1.setObjectName("edit1")
        self.player1_name = QtWidgets.QLabel(self.centralwidget)
        self.player1_name.setGeometry(QtCore.QRect(91, 121, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.player1_name.setFont(font)
        self.player1_name.setObjectName("player1_name")
        self.edit2 = QtWidgets.QTextEdit(self.centralwidget)
        self.edit2.setGeometry(QtCore.QRect(410, 140, 209, 290))
        self.edit2.setObjectName("edit2")
        self.player2_name = QtWidgets.QLabel(self.centralwidget)
        self.player2_name.setGeometry(QtCore.QRect(410, 121, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.player2_name.setFont(font)
        self.player2_name.setObjectName("player2_name")
        self.wordout = QtWidgets.QLabel(self.centralwidget)
        self.wordout.setGeometry(QtCore.QRect(120, 40, 106, 35))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.wordout.setFont(font)
        self.wordout.setObjectName("wordout")
        self.timer = QtWidgets.QLCDNumber(self.centralwidget)
        self.timer.setGeometry(QtCore.QRect(529, 29, 91, 41))
        self.timer.setObjectName("timer")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 40, 40, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.player1_start = QtWidgets.QPushButton(self.centralwidget)
        self.player1_start.setGeometry(QtCore.QRect(150, 450, 75, 23))
        self.player1_start.setObjectName("player1_start")
        self.player2_start = QtWidgets.QPushButton(self.centralwidget)
        self.player2_start.setGeometry(QtCore.QRect(490, 450, 75, 23))
        self.player2_start.setObjectName("player2_start")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(291, 501, 61, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(290, 542, 126, 50))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.player1_name_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.player1_name_2.setFont(font)
        self.player1_name_2.setObjectName("player1_name_2")
        self.horizontalLayout.addWidget(self.player1_name_2)
        self.player1_score = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.player1_score.setFont(font)
        self.player1_score.setObjectName("player1_score")
        self.horizontalLayout.addWidget(self.player1_score)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.player2_name_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.player2_name_2.setFont(font)
        self.player2_name_2.setObjectName("player2_name_2")
        self.horizontalLayout_2.addWidget(self.player2_name_2)
        self.player2_score = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.player2_score.setFont(font)
        self.player2_score.setObjectName("player2_score")
        self.horizontalLayout_2.addWidget(self.player2_score)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 702, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.player1 = ""
        self.player2 = ""

        self.edit1.setEnabled(False)
        self.edit2.setEnabled(False)
        self.c = 30
        self.v = False
        self.p1_list = ""
        self.p2_list = ""
        self.points_p1 = 0
        self.points_p2 = 0
        self.listc = []
        self.listv = []
        self.sublist = []
        self.words = [
            "BLUEPRINT", "TABLETOP", "WHEELBARROW", "TOUCHDOWN", "BOOKSTORE",
            "TEASPOON", "SLAPSTICK", "WATERWHEEL", "SUPERNATURAL",
            "COURTHOUSE", "HOMEMADE", "CLOCKWISE", "FIREWORKS", "FISHBOWL",
            "UPPERCLASSMAN", "COURTYARD", "NEWBORN", "MEANTIME", "RAILROAD",
            "UNDERDEVELOP", "BANANA"
        ]

        self.s = random.choice(self.words)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(
            _translate("MainWindow", "Let the Game begin"))
        self.label.setText(_translate("MainWindow", "Word:"))
        self.player1_name.setText(_translate("MainWindow", ""))
        self.player2_name.setText(_translate("MainWindow", ""))
        self.wordout.setText(_translate("MainWindow", "BANANA"))
        self.label_5.setText(_translate("MainWindow", "TImer:"))
        self.player1_start.setText(_translate("MainWindow", "START"))
        self.player2_start.setText(_translate("MainWindow", "START"))
        self.textBrowser.setHtml(
            _translate(
                "MainWindow",
                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Score:</span></p></body></html>"
            ))
        self.player1_name_2.setText(_translate("MainWindow", "Player1:"))
        self.player1_score.setText(_translate("MainWindow", "0"))
        self.player2_name_2.setText(_translate("MainWindow", "Player2:"))
        self.player2_score.setText(_translate("MainWindow", "0"))

    def start(self, t1, t2):
        self.wordout.setText(self.s)
        self.wordout.adjustSize()
        self.player1_name.setText(t1)
        self.player1_name.adjustSize()
        self.player2_name.setText(t2)
        self.player2_name.adjustSize()
        self.player1_name_2.setText(t1)
        self.player1_name_2.adjustSize()
        self.player2_name_2.setText(t2)
        self.player2_name_2.adjustSize()
        self.player1_start.clicked.connect(
            lambda: self.timer_create(self.player1_start, self.edit1))

        self.player2_start.clicked.connect(
            lambda: self.timer_create(self.player2_start, self.edit2))

    def timer_create(self, b, t):
        t.setEnabled(True)
        b.setEnabled(False)
        self.v = True
        self.ti = QtCore.QTimer()
        self.ti.timeout.connect(lambda: self.timer_display(t))
        self.ti.start(1000)

    def timer_display(self, t):
        if self.c != 0 and self.v:
            n = (self.c)
            self.timer.display(n)
            self.c -= 1

        elif self.c == 0:
            self.reset_timer()
            if t == self.edit1:
                self.p1_list = list(set(list(t.toPlainText().split())))
            elif t == self.edit2:
                self.p2_list = list(set(list(t.toPlainText().split())))
                self.substr_list()
            t.setEnabled(False)
            self.v = False

    def reset_timer(self):
        self.c = 30
        self.timer.display(0)

    def substr_list(self):
        for i in range(0, len(self.s)):
            self.sublist.append(self.s[i])
        for i in range(0, len(self.s) + 1):
            for j in range(i + 2, len(self.s) + 1):
                self.sublist.append(self.s[i:j])
        self.vowelncons()

    def vowelncons(self):
        vowels = ['a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U']
        for i in range(0, len(self.sublist)):
            if self.sublist[i][0] in vowels:
                self.listv.append(self.sublist[i])
            else:
                self.listc.append(self.sublist[i])
        self.point_calc()

    def point_calc(self):
        for i in range(0, len(self.p1_list)):
            for j in range(0, len(self.listc)):
                if self.p1_list[i] == self.listc[j]:
                    self.points_p1 += 1
                else:
                    pass

        for i in range(0, len(self.p2_list)):
            for j in range(0, len(self.listv)):
                if self.p2_list[i] == self.listv[j]:
                    self.points_p2 += 1
                else:
                    pass

        self.player1_score.setText(str(self.points_p1))
        self.player2_score.setText(str(self.points_p2))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     ui.start()
#     sys.exit(app.exec_())
